package part3;

import java.time.Instant;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;

public class Stringbufferandbuilder {
    public static void main(String args[]){

        StringBuffer stringBuffer = new StringBuffer("The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\n" +
                "So maybe someone else would say \" an article below 1000 characters isn't worthy for wikipedia \", and exclude many of your contributions.\n" +
                "The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\n" +
                "If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\n" +
                "Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\n" +
                "However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \" ( Beltrami, p . 108)\n" +
                "Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\n" +
                "However, check that the article content is acceptable; a formerly very short article that has grown to more than 1000 characters can indicate a mass introduction of text that may not belong.The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\n\" +\n" +
                "                \"So maybe someone else would say \\\" an article below 1000 characters isn't worthy for wikipedia \\\", and exclude many of your contributions.\\n\" +\n" +
                "                \"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\n\" +\n" +
                "                \"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\n\" +\n" +
                "                \"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\n\" +\n" +
                "                \"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\" ( Beltrami, p . 108)\\n\" +\n" +
                "                \"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\n\" +\n" +
                "                \"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\n\" +\n" +
                "                \"So maybe someone else would say \\\" an article below 1000 characters isn't worthy for wikipedia \\\", and exclude many of your contributions.\\n\" +\n" +
                "                \"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\n\" +\n" +
                "                \"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\n\" +\n" +
                "                \"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\n\" +\n" +
                "                \"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\" ( Beltrami, p . 108)\\n\" +\n" +
                "                \"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\n\" +\n" +
                "                \"However, check that the article content is acceptable; a formerly very short ");
        StringBuilder stringBuilder = new StringBuilder("[ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\n\" +\n" +
                "                \"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\n\" +\n" +
                "                \"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\" ( Beltrami, p . 108)\\n\" +\n" +
                "                \"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\n\" +\n" +
                "                \"However, check that the article content is acceptable; a formerly very short article that has grown to more than 1000 characters can indicate a mass introduction of text that may not belong.The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\n\" +\n" +
                "                \"So maybe someone else would say \\\" an article below 1000 characters isn't worthy for wikipedia \\\", and exclude many of your contributions.\\n\" +\n" +
                "                \"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\n\" +\n" +
                "                \"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\n\" +\n" +
                "                \"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\n\" +\n" +
                "                \"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\" ( Beltrami, p . 108)\\n\" +\n" +
                "                \"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\n\" +\n" +
                "                \"However, check that the article content is acceptable; a formerly very short article that has grown to more than 1000 characters can indicate a mass introduction of text that may not belong.The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\n\" +\n" +
                "                \"So maybe someone else would say \\\" an article below 1000 characters isn't worthy for wikipedia \\\", and exclude many of your contributions.\\n\" +\n" +
                "                \"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\n\" +\n" +
                "                \"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\n\" +\n" +
                "                \"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\n\" +\n" +
                "                \"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\" ( Beltrami, p . 108)\\n\" +\n" +
                "                \"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\n\" +\n" +
                "                \"However, check that the article content is acceptable; a formerly very short article that has grown to more than 1000 characters can indicate a mass introduction of text that may not belong.The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\n\" +\n" +
                "                \"So maybe someone else would say \\\" an article below 1000 characters isn't worthy for wikipedia \\\", and exclude many of your contributions.\\n\" +\n" +
                "                \"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\n\" +\n" +
                "                \"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\n\" +\n" +
                "                \"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\n\" +\n" +
                "                \"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\" ( Beltrami, p . 108)\\n\" +\n" +
                "                \"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\n\" +\n" +
                "                \"However, check that the article content is acceptable; a formerly very short article that has grown to more than 1000 characters can indicate a mass introduction of text that may not belong.The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\n\" +\n" +
                "                \"So maybe someone else would say \\\" an article below 1000 characters isn't worthy for wikipedia \\\", and exclude many of your contributions.\\n\" +\n" +
                "                \"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\n\" +\n" +
                "                \"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\n\" +\n" +
                "                \"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\n\" +\n" +
                "                \"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\" ( Beltrami, p . 108)\\n\" +\n" +
                "                \"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\n\" +\n" +
                "                \"However, check that the article content is acceptable; a formerly very short article that has grown to more than 1000 characters can indicate a mass introduction of text that may not belong.The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\n\" +\n" +
                "                \"So maybe someone else would say \\\" an article below 1000 characters isn't worthy for wikipedia \\\", and exclude many of your contributions.\\n\" +\n" +
                "                \"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\n\" +\n" +
                "                \"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\n\" +\n" +
                "                \"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\n\" +\n" +
                "                \"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\" ( Beltrami, p . 108)\\n\" +\n" +
                "                \"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\n\" +\n" +
                "                \"However, check that the article content is acceptable; a formerly very short article that has grown to more than 1000 characters can indicate a mass introduction of text that may not belong.The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\n\" +\n" +
                "                \"So maybe someone else would say \\\" an article below 1000 characters isn't worthy for wikipedia \\\", and exclude many of your contributions.\\n\" +\n" +
                "                \"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\n\" +\n" +
                "                \"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\n\" +\n" +
                "                \"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\n\" +\n" +
                "                \"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\" ( Beltrami, p . 108)\\n\" +\n" +
                "                \"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\n\" +\n" +
                "                \"However, check that the article content is acceptable; a formerly very short article that has grown to more than 1000 characters can indicate a mass introduction of text that may not belong.The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\n\" +\n" +
                "                \"So maybe someone else would say \\\" an article below 1000 characters isn't worthy for wikipedia \\\", and exclude many of your contributions.\\n\" +\n" +
                "                \"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\n\" +\n" +
                "                \"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\n\" +\n" +
                "                \"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\n\" +\n" +
                "                \"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\" ( Beltrami, p . 108)\\n\" +\n" +
                "                \"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\n\" +\n" +
                "                \"However, check that the article content is acceptable; a formerly very short article that has grown to more than 1000 characters can indicate a mass introduction of text that may not belong.The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\n\" +\n" +
                "                \"So maybe someone else would say \\\" an article below 1000 characters isn't worthy for wikipedia \\\", and exclude many of your contributions.\\n\" +\n" +
                "                \"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\n\" +\n" +
                "                \"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\n\" +\n" +
                "                \"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\n\" +\n" +
                "                \"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\" ( Beltrami, p . 108)\\n\" +\n" +
                "                \"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\n\" +\n" +
                "                \"However, check that the article content is acceptable; a formerly very short article that has grown to more than 1000 characters can indicate a mass introduction of text that may not belong.The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\n\" +\n" +
                "                \"So maybe someone else would say \\\" an article below 1000 characters isn't worthy for wikipedia \\\", and exclude many of your contributions.\\n\" +\n" +
                "                \"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\n\" +\n" +
                "                \"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\n\" +\n" +
                "                \"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\n\" +\n" +
                "                \"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\" ( Beltrami, p . 108)\\n\" +\n" +
                "                \"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\n\" +\n" +
                "                \"However, check that the article content is acceptable; a formerly very short article that has grown to more than 1000 characters can indicate a mass introduction of text that may not belong.The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\n\" +\n" +
                "                \"So maybe someone else would say \\\" an article below 1000 characters isn't worthy for wikipedia \\\", and exclude many of your contributions.\\n\" +\n" +
                "                \"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\n\" +\n" +
                "                \"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\n\" +\n" +
                "                \"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\n\" +\n" +
                "                \"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\" ( Beltrami, p . 108)\\n\" +\n" +
                "                \"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\n\" +\n" +
                "                \"However, check that the article content is acceptable; a formerly very short article that has grown to more than 1000 characters can indicate a mass introduction of text that may not belong.The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\n\" +\n" +
                "                \"So maybe someone else would say \\\" an article below 1000 characters isn't worthy for wikipedia \\\", and exclude many of your contributions.\\n\" +\n" +
                "                \"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\n\" +\n" +
                "                \"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\n\" +\n" +
                "                \"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\n\" +\n" +
                "                \"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\" ( Beltrami, p . 108)\\n\" +\n" +
                "                \"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\n\" +\n" +
                "                \"However, check that the article content is acceptable; a formerly very short article that has grown to more than 1000 characters can indicate a mass introduction of text that may not belong.The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\n\" +\n" +
                "                \"So maybe someone else would say \\\" an article below 1000 characters isn't worthy for wikipedia \\\", and exclude many of your contributions.\\n\" +\n" +
                "                \"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\n\" +\n" +
                "                \"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\n\" +\n" +
                "                \"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\n\" +\n" +
                "                \"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\" ( Beltrami, p . 108)\\n\" +\n" +
                "                \"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\n\" +\n" +
                "                \"However, check that the article content is acceptable; a formerly very short article that has grown to more than 1000 characters can indicate a mass introduction of text that may not belong.The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\n\" +\n" +
                "                \"So maybe someone else would say \\\" an article below 1000 characters isn't worthy for wikipedia \\\", and exclude many of your contributions.\\n\" +\n" +
                "                \"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\n\" +\n" +
                "                \"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\n\" +\n" +
                "                \"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\n\" +\n" +
                "                \"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\" ( Beltrami, p . 108)\\n\" +\n" +
                "                \"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\n\" +\n" +
                "                \"However, check that the article content is acceptable; a formerly very short article that has grown to more than 1000 characters can indicate a mass introduction of text that may not belong.The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\n\" +\n" +
                "                \"So maybe someone else would say \\\" an article below 1000 characters isn't worthy for wikipedia \\\", and exclude many of your contributions.\\n\" +\n" +
                "                \"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\n\" +\n" +
                "                \"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\n\" +\n" +
                "                \"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\n\" +\n" +
                "                \"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\" ( Beltrami, p . 108)\\n\" +\n" +
                "                \"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\n\" +\n" +
                "                \"However, check that the article content is acceptable; a formerly very short article that has grown to more than 1000 characters can indicate a mass introduction of text that may not belong.The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say \\\\\\\" an article below 1000 characters isn't worthy for wikipedia \\\\\\\", and exclude many of your contributions.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"The article has come down in length by about 1000 characters in the last year, presumably by the selective removal of non-notable subject matter.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"If S [ ] is 1 billion characters and W [ ] is 1000 characters, then the string search should complete after about one billion character comparisons.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Comments longer than 1000 characters, responses to the comments of others and general discussion of the topic were to go in the discussion section, lower down the page.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, the sentence within quotation marks, which is itself a definition of the alleged number is less than 1000 characters in length ! \\\\\\\" ( Beltrami, p . 108)\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"Memory could be, but even 1 MB of memory could handle maybe a thousand questions, at 1000 characters each, so that doesn't seem to be an issue.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"However, check that the article content is acceptable; a formerly very short The simple string matching algorithm will now examine 1000 characters at each trial position before rejecting the match and advancing the trial position.\\\\n\\\" +\\n\" +\n" +
                "                \"                \\\"So maybe someone else would say");
        float startTime = Date.from(Instant.now()).getTime();
        System.out.println(Date.from(Instant.now()).getTime());
        stringBuffer.charAt(3000);
        System.out.println(Date.from(Instant.now()).getTime());



        System.out.println();

        float startTimeBuilder = Date.from(Instant.now()).getTime();
        System.out.println(Date.from(Instant.now()).getTime());
        stringBuilder.charAt(30000);
        System.out.println(Date.from(Instant.now()).getTime());

    }
}
